version: 2
snapshot:
  widths:
    - 640
    - 960
    - 1280
  minHeight: 1024
  percyCSS: ''
discovery:
  allowedHostnames: []
  networkIdleTimeout: 100
  disableCache: false
static:
  baseUrl: /
  files: '**/*.{html,htm}'
  ignore: ''
upload:
  files: '**/*.{png,jpg,jpeg}'
  ignore: ''
