name: Deploy
on:
  push:
    branches:
      - master
jobs:
  storybook:
    name: Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn run build
      - run: yarn run build-storybook
      - run: yarn storybook-to-ghpages --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: aesthetic-suite:${{ secrets.GITHUB_TOKEN }}
