name: PR
on: pull_request
jobs:
  conventional:
    name: Conventional Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: beemojs/conventional-pr-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  storybook:
    name: Publish Storybook
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npx storybook-to-ghpages --ci
